import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
    children: React.ReactNode;
}

export default function RootLayout({children,}: Readonly<RootLayoutProps>) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <header>
          <h1>Header</h1>
      </header>
        <div className={`bg-red-500`}>{children}</div>
      <footer>
          <h1>Footer</h1>
      </footer>
      </body>
    </html>
  );
}
